Diplom add project tests
naumalex/TestRail_Alexander_Naumovets pull request #2
Opened 2022-09-14 18:29 UTC by naumalex

2022-09-14 18:40 UTC, voropa requested changes

2022-09-14 18:40 UTC, voropa commented on src/test/java/pages/project/ProjectsPage.java
> +        wait.until(ExpectedConditions.elementToBeClickable(deleteIcon));
У вас много где  используется подобное ожидание, вынесите его в отдельный метод в Base класс: waitForElementToBeClickable(WebEleement element)

2022-09-14 20:59 UTC, naumalex commented on src/test/java/pages/project/ProjectsPage.java
> +        wait.until(ExpectedConditions.elementToBeClickable(deleteIcon));
fixed

2022-09-14 21:20 UTC, voropa approved these changes

2022-09-15 08:31 UTC, voropa approved these changes

2022-09-16 06:18 UTC, merged