Tests have completed
naumalex/TestRail_Alexander_Naumovets pull request #3
Opened 2022-09-18 11:16 UTC by naumalex

2022-09-18 19:35 UTC, voropa requested changes

2022-09-18 19:35 UTC, voropa commented on src/test/java/tests/TestRunTests.java
> +        driver.navigate().refresh();
Избегайте использования драйвера в тестовых методах. Лучше сделайте в basePage / baseStep классе метод reloadPage() и вызывайте его тут.

2022-09-18 19:35 UTC, voropa commented on src/test/java/tests/TestRunTests.java
> +        testCases.stream().forEach(projectDetailsSteps::addTestCaseViaSideBar);
Тут тоже некрасиво, что в тестах используется stream() и forEach, лучше сделайте внутри step метода эту логику с forEach а в этот метод передавайте массив testCases снаружи.

2022-09-19 18:15 UTC, naumalex commented on src/test/java/tests/TestRunTests.java
> +        testCases.stream().forEach(projectDetailsSteps::addTestCaseViaSideBar);
Fixed.

2022-09-19 18:15 UTC, naumalex commented on src/test/java/tests/TestRunTests.java
> +        driver.navigate().refresh();
Fixed.

2022-09-19 18:26 UTC, voropa approved these changes

2022-09-19 20:22 UTC, voropa requested changes

2022-09-19 20:22 UTC, voropa commented on Readme.md.txt
> +**Product description**
Расширение у readme файла должно быть просто .md, без .txt

2022-09-19 20:27 UTC, voropa requested changes

2022-09-19 20:27 UTC, voropa commented on src/test/java/tests/TestRunTests.java
> +        driver.navigate().refresh();
Поправьте тут то же самое, что и в предыдущем тесте: driver.navigate.refresh() и testCases.stream().forEach(projectDetailsSteps::addTestCaseViaSideBar);

2022-09-19 20:41 UTC, voropa requested changes

2022-09-19 20:41 UTC, voropa commented on src/test/java/tests/TestRunTests.java
> +        ApiUtils.deleteProjectsIfExists(PROJECT_NAME);
Это лучше вынести в afterMethod/Class, тем более, что у вас в обоих тестах в конце выполняется это действие.

2022-09-19 20:46 UTC, voropa reviewed
Запускал ваши тесты несколько раз, постоянно ппадают TestCasesTests по 2-3 штуки, причем с разными ошибками всегда

2022-09-19 23:19 UTC, naumalex commented on Readme.md.txt
> +**Product description**
fixed.

2022-09-19 23:19 UTC, naumalex commented on src/test/java/tests/TestRunTests.java
> +        driver.navigate().refresh();
fixed

2022-09-19 23:25 UTC, naumalex commented on src/test/java/tests/TestRunTests.java
> +        ApiUtils.deleteProjectsIfExists(PROJECT_NAME);
здесь просто описка была. Должно быть deleteProjectsIfExists(projectName). Каждый тест из этих 2 тестов создает свой проект с уникальным именем (projectName), которое существует в рамках этого теста. Соответственно, действие не совсем одинаковое, удаляются разные проекты.

2022-09-19 23:29 UTC, naumalex commented
> Запускал ваши тесты несколько раз, постоянно ппадают TestCasesTests по 2-3 штуки, причем с разными ошибками всегда

АН: Думаю, исправил. Последующий тест по ошибке удалял нужный этим тестам проект, выполняясь в другом потоке во время их выполнения.

2022-09-20 08:34 UTC, voropa commented on src/test/java/tests/TestRunTests.java
> +        driver.navigate().refresh();
testCases.stream().forEach(projectDetailsSteps::addTestCaseViaSideBar); - тоже замените на projectDetailsStepsюaddTestCasesViaSlideBar(testCases)

2022-09-20 08:34 UTC, voropa commented on src/test/java/tests/TestRunTests.java
> +        ApiUtils.deleteProjectsIfExists(PROJECT_NAME);
Но теперь у вас как раз таки одинаковая переменная передается в этот метод для удаления, значит можно вынести эту переменную на уровень класса, в каждом тесте ее переприсваивать, и метод по удалению внести в afterMethod()
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/14195681/191209083-3ffe46b9-d3cd-40eb-9ee4-e32f11cf8e3f.png">

2022-09-20 21:40 UTC, naumalex commented on src/test/java/tests/TestRunTests.java
> +        ApiUtils.deleteProjectsIfExists(PROJECT_NAME);
fixed

2022-09-20 21:41 UTC, naumalex commented on src/test/java/tests/TestRunTests.java
> +        driver.navigate().refresh();
Fixed.

2022-09-21 06:37 UTC, voropa approved these changes

2022-09-22 17:09 UTC, merged